### ISSUE TITLE
Problem with Emailer

### ISSUE THREAD

**Issue by RonB26** [bradymholt/vistaicm-server#6]
Hello Mr holt,

First, thanks so much for this program, works really good.

I seem to be having an issue with the emailer script. I'm getting the following error:

i@raspberrypi:~/vistaicm-server-master $ sudo ./run
Starting server ...

> vistaicm-server@1.0.0 dev /home/pi/vistaicm-server-master/src
> ts-node-dev ./boot.ts

Using ts-node version 8.10.1, typescript version 3.9.3
Booting vistaicm-server
Loading hooks
   log-events.js [ok]
   send-email-on-alarm.jsTypeError: Cannot create property 'mailer' on string 'SMTP'
    at new Mail (/home/pi/node_modules/nodemailer/lib/mailer/index.js:45:33)
    at Object.module.exports.createTransport (/home/pi/node_modules/nodemailer/lib/nodemailer.js:53:14)
    at Object.<anonymous> (/home/pi/vistaicm-server-master/src/hooks/send-email-on-alarm.js:3:32)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/home/pi/vistaicm-server-master/src/node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.nodeDevHook [as .js] (/home/pi/vistaicm-server-master/src/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
[ERROR] 20:17:07 TypeError: Cannot create property 'mailer' on string 'SMTP'

Any idea what I need to do to fix this?

Thanks in advance,
Ron B

**Comment by bradymholt** [comment]
It looks like you may be using a newer version of node-mailer.  You'll probably have to downgrade or update that hook to use the [latest node-mailer interface](https://nodemailer.com/usage/).
